import { PageCta, SiteFooter, SiteHeader } from "../site-chrome";
import { assetPath } from "../asset-path";

const incidents = [
  { year: "2006", icon: "/icons/nuclear/radiation-hq.png", place: "Sterigenics, Fleurus — Belgium", level: "INES 4", title: "Worker irradiation accident", body: "An operator entered an irradiation cell containing cobalt-60 sources and received a very high dose. FANC documents an accident affecting the worker, not a general exposure of the population.", use: "The voicebot can explain the difference between irradiation and contamination, prevent unsupported extrapolation to a public hazard and direct suspected exposure to 112.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-en-belgique/dans-le-secteur-industriel-sterigenics-fleurus" },
  { year: "2008", icon: "/icons/nuclear/toxic-cloud-hq.png", place: "IRE, Fleurus — Belgium", level: "INES 3", title: "Abnormal radioactive-iodine release", body: "An incorrect transfer of effluent caused an atmospheric release of radioactive iodine. The nuclear and radiological emergency plan was activated as a precaution, and local recommendations were issued.", use: "The voicebot can rapidly repeat an already approved local instruction, stress that iodine tablets require authority direction and reduce pressure on human information lines.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-en-belgique/dans-le-secteur-nucleaire-ire-fleurus" },
  { year: "1986", icon: "/icons/nuclear/explosion-hq.png", place: "Chornobyl — Ukraine", level: "INES 7", title: "Major nuclear accident", body: "The Reactor 4 accident caused large-scale radioactive releases and cross-border consequences in Europe. It remains an important case for international radiological monitoring.", use: "The voicebot can distinguish monitoring data from rumour, explain why distance alone is insufficient and relay Belgian decisions without interpreting technical maps.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-letranger/1986-accident-nucleaire-de-tchernobyl" },
  { year: "2011", icon: "/icons/nuclear/pollution-hq.png", place: "Fukushima Daiichi — Japan", level: "INES 7", title: "Major nuclear accident", body: "Following the earthquake and tsunami, several units at the plant sustained severe damage. The event is documented by FANC and the IAEA.", use: "The voicebot can explain that an event abroad does not automatically require a protective measure in Belgium and refer only to current official assessments.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-letranger/2011-accident-nucleaire-de-fukushima" },
];

export default function Incidents() {
  return <main>
    <SiteHeader active="incidents" />
    <section className="subpage-hero shell"><p className="kicker accent">Official timeline</p><h1>Historical facts,<br />never current alerts.</h1><div className="lead"><p>This selection is deliberately limited to events documented by FANC. INES levels support communication about an event; they are not a means of comparing the safety of installations.</p></div></section>
    <section className="band band-cool"><div className="shell incident-list">{incidents.map((incident) => <article className="incident-item" key={incident.year + incident.place}><div className="incident-year"><time>{incident.year}</time><span>{incident.level}</span></div><img src={assetPath(incident.icon)} alt="" /><div><p className="kicker accent">{incident.place}</p><h2>{incident.title}</h2><p>{incident.body}</p><aside className="incident-use"><strong>How the voicebot can help</strong>{incident.use}</aside><a className="official-link" href={incident.url} target="_blank" rel="noreferrer">Read the official FANC record</a></div></article>)}</div></section>
    <PageCta />
    <SiteFooter />
  </main>;
}
