import Link from "next/link";

const incidents = [
  {year:"2006",place:"Sterigenics, Fleurus — Belgique",level:"INES 4",title:"Accident d’irradiation",body:"Un opérateur est entré dans une cellule d’irradiation contenant des sources de cobalt soixante et a reçu une dose très élevée. L’AFCN documente un accident touchant le travailleur, pas une exposition générale de la population.",use:"Le bot peut expliquer la différence entre irradiation et contamination, empêcher les extrapolations vers un danger public non confirmé et orienter une exposition suspectée vers le 112.",url:"https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-en-belgique/dans-le-secteur-industriel-sterigenics-fleurus"},
  {year:"2008",place:"IRE, Fleurus — Belgique",level:"INES 3",title:"Rejet anormal d’iode radioactif",body:"Un transfert erroné d’effluents a provoqué un rejet atmosphérique d’iode radioactif. Le plan d’urgence nucléaire et radiologique a été déclenché par précaution et des recommandations locales ont été émises.",use:"Le bot peut répéter rapidement une consigne géolocalisée déjà approuvée, rappeler que les comprimés d’iode ne se prennent que sur instruction et limiter la saturation des lignes humaines.",url:"https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-en-belgique/dans-le-secteur-nucleaire-ire-fleurus"},
  {year:"1986",place:"Tchernobyl — Ukraine",level:"INES 7",title:"Accident nucléaire majeur",body:"L’accident du réacteur quatre a entraîné des rejets radioactifs à grande échelle et des conséquences transfrontalières en Europe. Il reste un cas de référence pour la surveillance radiologique internationale.",use:"Le bot peut distinguer les mesures observées des rumeurs, expliquer pourquoi une distance seule ne suffit pas et relayer les décisions belges sans interpréter des cartes techniques.",url:"https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-letranger/1986-accident-nucleaire-de-tchernobyl"},
  {year:"2011",place:"Fukushima Daiichi — Japon",level:"INES 7",title:"Accident nucléaire majeur",body:"Après le séisme et le tsunami, plusieurs unités de la centrale ont subi de graves dommages. L’événement est documenté par l’AFCN et l’AIEA.",use:"Le bot peut expliquer qu’un événement étranger n’implique pas automatiquement une mesure en Belgique et renvoyer uniquement aux évaluations officielles actuelles.",url:"https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-letranger/2011-accident-nucleaire-de-fukushima"},
];
export default function Incidents(){return <main><PageNav/><section className="subhero shell"><p className="kicker">CHRONOLOGIE OFFICIELLE</p><h1>Des faits historiques,<br/>jamais des alertes actuelles.</h1><p>Cette sélection est volontairement limitée aux événements décrits par l’AFCN. Les niveaux INES facilitent la communication sur un événement ; l’AFCN précise qu’ils ne servent pas à comparer la sûreté des installations.</p></section><section className="section shell"><div className="incident-list">{incidents.map(x=><article key={x.year+x.place}><div><time>{x.year}</time><span>{x.level}</span></div><div><p className="kicker">{x.place}</p><h2>{x.title}</h2><p>{x.body}</p><aside><strong>Comment le voicebot peut être utile</strong>{x.use}</aside><a href={x.url} target="_blank" rel="noreferrer">Lire la fiche officielle AFCN ↗</a></div></article>)}</div></section></main>}
function PageNav(){return <header className="nav shell"><Link className="brand" href="/"><span className="brand-mark">N</span><span>Info Nucléaire<br/><small>Belgique</small></span></Link><nav><Link className="active" href="/incidents">Incidents</Link><Link href="/sources">Sources</Link><Link href="/architecture">Architecture</Link></nav><Link className="nav-cta" href="/">Accueil</Link></header>}
