import { PageCta, SiteFooter, SiteHeader } from "../site-chrome";

const incidents = [
  { year: "2006", icon: "/icons/nuclear/warning.png", place: "Sterigenics, Fleurus — Belgique", level: "INES 4", title: "Accident d’irradiation", body: "Un opérateur est entré dans une cellule d’irradiation contenant des sources de cobalt 60 et a reçu une dose très élevée. L’AFCN documente un accident touchant le travailleur, pas une exposition générale de la population.", use: "Le bot peut expliquer la différence entre irradiation et contamination, empêcher les extrapolations vers un danger public non confirmé et orienter une exposition suspectée vers le 112.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-en-belgique/dans-le-secteur-industriel-sterigenics-fleurus" },
  { year: "2008", icon: "/icons/nuclear/toxic-cloud.png", place: "IRE, Fleurus — Belgique", level: "INES 3", title: "Rejet anormal d’iode radioactif", body: "Un transfert erroné d’effluents a provoqué un rejet atmosphérique d’iode radioactif. Le plan d’urgence nucléaire et radiologique a été déclenché par précaution et des recommandations locales ont été émises.", use: "Le bot peut répéter rapidement une consigne géolocalisée déjà approuvée, rappeler que les comprimés d’iode ne se prennent que sur instruction et limiter la saturation des lignes humaines.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-en-belgique/dans-le-secteur-nucleaire-ire-fleurus" },
  { year: "1986", icon: "/icons/nuclear/explosion.png", place: "Tchernobyl — Ukraine", level: "INES 7", title: "Accident nucléaire majeur", body: "L’accident du réacteur 4 a entraîné des rejets radioactifs à grande échelle et des conséquences transfrontalières en Europe. Il reste un cas de référence pour la surveillance radiologique internationale.", use: "Le bot peut distinguer les mesures observées des rumeurs, expliquer pourquoi une distance seule ne suffit pas et relayer les décisions belges sans interpréter des cartes techniques.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-letranger/1986-accident-nucleaire-de-tchernobyl" },
  { year: "2011", icon: "/icons/nuclear/pollution.png", place: "Fukushima Daiichi — Japon", level: "INES 7", title: "Accident nucléaire majeur", body: "Après le séisme et le tsunami, plusieurs unités de la centrale ont subi de graves dommages. L’événement est documenté par l’AFCN et l’AIEA.", use: "Le bot peut expliquer qu’un événement étranger n’implique pas automatiquement une mesure en Belgique et renvoyer uniquement aux évaluations officielles actuelles.", url: "https://afcn.fgov.be/fr/situations-durgence/evenements-majeurs-letranger/2011-accident-nucleaire-de-fukushima" },
];

export default function Incidents() {
  return <main>
    <SiteHeader active="incidents" />
    <section className="subpage-hero shell"><p className="kicker accent">Chronologie officielle</p><h1>Des faits historiques,<br />jamais des alertes actuelles.</h1><div className="lead"><p>Cette sélection est volontairement limitée aux événements décrits par l’AFCN. Les niveaux INES facilitent la communication sur un événement ; l’AFCN précise qu’ils ne servent pas à comparer la sûreté des installations.</p></div></section>
    <section className="band band-cool"><div className="shell incident-list">{incidents.map((incident) => <article className="incident-item" key={incident.year + incident.place}><div className="incident-year"><time>{incident.year}</time><span>{incident.level}</span></div><img src={incident.icon} alt="" /><div><p className="kicker accent">{incident.place}</p><h2>{incident.title}</h2><p>{incident.body}</p><aside className="incident-use"><strong>Comment le Voicebot peut être utile</strong>{incident.use}</aside><a className="official-link" href={incident.url} target="_blank" rel="noreferrer">Lire la fiche officielle AFCN</a></div></article>)}</div></section>
    <PageCta />
    <SiteFooter />
  </main>;
}
